<?php if($_SESSION['autoriziran']->uloga==='doktor'): ?>
<a class="btn btn-outline-secondary" href="#">Dodaj novu ordinaciju</a>
<?php endif; ?>

<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Popis ordinacija</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($ordinacije as $ordinacija): ?>
        <tr>
            <td><?=$ordinacija->naziv?></td>
        </tr>
    <?php endforeach; ?>
  </tbody>
</table>