<div class="container center_div">
    <div class="div-wrapper d-flex justify-content-center align-items-center">
        <form action="<?=APP::config('url') ?>ordinacija/novi" method="POST">
            
            <h1 class="h3 mb-3 font-weight-normal">Dodaj novu ordinaciju</h1>

            <div class="form-group">
                <label>Naziv ordinacije:
                    <input type="text" name="naziv" class="form-control text-center">
                </label>    
                <br>    
            </div>
            <a class="btn btn-secondary" href="<?=APP::config('url') ?>ordinacija/index">Odustani</a>               
            <button class="btn btn-primary" type="submit">Unesi</button>
            
            <br>
        </form>
    </div>
</div>