<div class="container center_div">
    <div class="div-wrapper d-flex justify-content-center align-items-center">
        <form action="<?=APP::config('url') ?>ordinacija/promjena" method="POST">
            
            <h1 class="h3 mb-3 font-weight-normal">Uredi naziv ordinacije</h1>

            <div class="form-group">
                <label>Naziv ordinacije:
                    <input type="text" name="naziv" class="form-control text-center" value="<?=$ordinacija->naziv?>">
                </label>    
                <br>    
            </div>

            <input type="hidden" name="sifra" value="<?=$ordinacija->sifra ?>">

            <a class="btn btn-secondary" href="<?=APP::config('url') ?>ordinacija/index">Odustani</a>              
            <button class="btn btn-primary" type="submit">Promijeni</button>
            
            <br>
        </form>
    </div>
</div>