<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Popis termina</th>
    </tr>
    <tr>
      <th scope="col">Pacijent:</th>
      <th scope="col">Doktor:</th>
      <th scope="col">Termin:</th>
    </tr>
  </thead>
  <tbody>
    <?php foreach($entiteti as $entitet): ?>
      <tr>
        <td><?=$entitet->pacijent?></td>
        <td><?=$entitet->doktor?></td>
        <td><?=$entitet->datum?></td>
        <?php if($_SESSION['autoriziran']->uloga==='doktor'): ?>
          <td>
                      
            <a onclick="return confirm('Sigurno obrisati?');"
              href="<?=APP::config('url') ?>termin/brisanje?sifra=<?=$entitet->sifra?>">
              <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
            </a>
          
          </td>
        <?php endif; ?>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<hr>

<?php if($_SESSION['autoriziran']->uloga==='doktor'): ?>
  <a class="btn btn-outline-secondary" href="<?=APP::config('url') ?>termin/novi">Dodaj novi termin</a>
<?php endif; ?>