<form action="<?=APP::config('url') ?>termin/novi" method="POST">
    <h1 class="h3 mb-3 font-weight-normal">Dodaj novi termin</h1>
    <div class="form-row">    
        <div class="form-group col-md-4">
            <label for="inputEmail4">Ime:</label>
            <select id="inputState" class="form-control">
                <option selected>Odaberi...</option>
                <?php foreach($pacijenti as $pacijent): ?>
                <option <?php if($entitet->ime==$pacijent->sifra){ echo ' selected="selected" ';}?> 
                value="<?=$pacijent->sifra?>"><?=$pacijent->ime?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group col-md-4">
            <label for="inputPassword4">Prezime:</label>
            <<select id="inputState" class="form-control">
                <option selected>Odaberi...</option>
                <?php foreach($pacijenti as $pacijent): ?>
                <option <?php if($entitet->prezime==$pacijent->sifra){ echo ' selected="selected" ';}?> 
                value="<?=$pacijent->sifra?>"><?=$pacijent->prezime?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group col-md-4">
            <label for="inputAddress">MBO:</label>
            <input type="text" class="form-control" id="inputAddress" value="<?=$entitet->mbo?>">
        </div>
    </div>
    <div class="form-row">     
        <div class="form-group col-md-6">
        <label for="inputState">Ordinacija:</label>
            <select id="inputState" class="form-control">
                <option selected>Odaberi...</option>
                <option selected>Odaberi...</option>
                <?php foreach($ordinacije as $ordinacija): ?>
                <option <?php if($entitet->ordinacija==$ordinacija->sifra){ echo ' selected="selected" ';}?> 
                value="<?=$ordinacija->sifra?>"><?=$ordinacija->naziv?></option>
                <?php endforeach; ?>
            </select>
        </div>
        <div class="form-group col-md-6">
        <label for="inputState">Doktor:</label>
            <select id="inputState" class="form-control">
            <option selected>Odaberi...</option>
                <?php foreach($doktori as $doktor): ?>
                <option <?php if($entitet->doktor==$doktor->sifra){ echo ' selected="selected" ';}?> 
                value="<?=$doktor->sifra?>"><?=$doktor->ime?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form row">
        <div class="form-froup col-md-6">
            <label for="example-date-input" >Termin:</label>        
            <input class="form-control" type="datetime-local" id="example-date-input" name="datum">            
        </div>
    </div>
    
    <a class="btn btn-secondary" href="<?=APP::config('url') ?>termin/index">Odustani</a>
    <button type="submit" class="btn btn-primary">Zakaži termin</button>
</form>