<form action="<?=APP::config('url') ?>termin/promjena" method="POST">
    <h1 class="h3 mb-3 font-weight-normal">Promijeni termin</h1>
    <div class="form-row">    
        <div class="form-group col-md-4">
            <label for="inputEmail4">Pacijent:</label>
            <select name="pacijent" id="inputState" class="form-control">
                <option selected>Odaberi...</option>
                <?php foreach($pacijenti as $pacijent): ?>
                <option <?php if($entitet->pacijent==$pacijent->sifra){ echo ' selected="selected" ';}?> 
                value="<?=$pacijent->sifra?>"><?=$pacijent->ime?> <?=$pacijent->prezime?></option>
                <?php endforeach; ?>
            </select>
        </div>
        
        
    </div>
    <div class="form-row">     
        <div class="form-group col-md-6">
        <label for="inputState">Doktor:</label>
            <select name="doktor" id="inputState" class="form-control">
            <option selected>Odaberi...</option>
                <?php foreach($doktori as $doktor): ?>
                <option <?php if($entitet->doktor==$doktor->sifra){ echo ' selected="selected" ';}?> 
                value="<?=$doktor->sifra?>"><?=$doktor->ime?> <?=$doktor->prezime?></option>
                <?php endforeach; ?>
            </select>
        </div>
    </div>

    <div class="form row">
        <div class="form-froup col-md-6">
            <label for="example-date-input" >Termin:</label>        
            <input class="form-control" type="datetime-local" id="example-date-input" name="datum">            
        </div>
    </div>
    
    <a class="btn btn-secondary" href="<?=APP::config('url') ?>termin/index">Odustani</a>
    <button type="submit" class="btn btn-primary">Promijeni</button>
</form>