<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title><?=APP::config('nazivAPP') ?>   </title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>

<link rel="stylesheet" href="<?=APP::config('url') ?>/public/ /favicon/apple-icon-57x57.png">

<link rel="apple-touch-icon" sizes="57x57" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="<?=APP::config('url') ?>/public/img/favicon/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="<?=APP::config('url') ?>/public/img/favicon/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="<?=APP::config('url') ?>/public/img/favicon/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="<?=APP::config('url') ?>/public/img/favicon/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="<?=APP::config('url') ?>/public/img/favicon/favicon-16x16.png">
<link rel="manifest" href="<?=APP::config('url') ?>/public/img/favicon/manifest.json">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="<?=APP::config('url') ?>/public/img/favicon/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">