<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="<?=APP::config('url') ?>"> <?=APP::config('nazivAPP') ?></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="navbar-collapse collapse w-100 order-3 dual-collapse2" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="<?=APP::config('url') ?>index/onama">O nama</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="<?=APP::config('url') ?>index/kontakt">Kontakt</a>
      </li>
      
      <?php if(isset($_SESSION['autoriziran'])): ?> 
        <li class="nav-item">
                <a class="nav-link" href="<?=APP::config('url') ?>nadzornaploca/index">Nadzorna ploča</a>
              </li>

              <?php if($_SESSION['autoriziran']->uloga==='doktor'): ?>
                <li class="nav-item">
                <a class="nav-link" href="<?=APP::config('url') ?>doktor/index">Doktori</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?=APP::config('url') ?>pacijent/index">Pacijenti</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<?=APP::config('url') ?>termin/index">Termini</a>
              </li>
              <?php endif; ?>

              <?php if($_SESSION['autoriziran']->uloga==='pacijent'): ?>
                <li class="nav-item">
                  <a class="nav-link" href="<?=APP::config('url') ?>ordinacija/index">Ordinacije</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<?=APP::config('url') ?>doktor/index">Doktori</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="<?=APP::config('url') ?>termin/index">Termini</a>
                </li>
              <?php endif; ?>
            <?php endif; ?>

            <?php if(!isset($_SESSION['autoriziran'])): ?> 
              <li class="nav-item">
                <a class="nav-link" href="<?=APP::config('url') ?>index/login">Login</a>
              </li>
            <?php else: ?>
              <li class="nav-item">
                <a class="nav-link" href="<?=APP::config('url') ?>index/logout">Logout
                  <?=$_SESSION['autoriziran']->uloga?>
                  <?=$_SESSION['autoriziran']->ime?>
                </a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="<?=APP::config('url') ?>nadzornaploca/profil"><i class="fas fa-user"></i></a>
              </li>
            <?php endif; ?>
  </div>
</nav>