<div class= 'large-12 small-12'>
            <div class='card'>
                <div class='container'<?php
                    if(App::config('dev')){
                        echo 'style="background-color: AntiqueWhite;"';
                    }
                ?>>
                    &copy; <?=APP::config('nazivAPP') ?> <?php echo date('Y'); ?>
                </div>                
            </div>            
        </div>
