<table class="table table-borderless">
  <thead>
    <tr>
      <th scope="col">Popis doktora</th>
    </tr>
  </thead>
  
  <tbody>
    <?php foreach($entiteti as $entitet): ?>
      <tr>
        <td><?=$entitet->ime?></td>
        <td><?=$entitet->prezime?></td>
        <td><?=$entitet->naziv?></td>
        <?php if($_SESSION['autoriziran']->uloga==='doktor'): ?>
          <td>
            <a href="<?=APP::config('url') ?>doktor/promjena?sifra=<?=$entitet->sifra?>">
              <?php include BP . 'view/predlozak/izgledPromijeni.phtml' ?>
            </a>
            
            <a href="<?=APP::config('url') ?>doktor/brisanje?sifra=<?=$entitet->sifra?>">
              <?php include BP . 'view/predlozak/izgledObrisi.phtml' ?>
            </a>
          </td>
        <?php endif; ?> 
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>

<hr>

<?php if($_SESSION['autoriziran']->uloga==='doktor'): ?>
<a class="btn btn-outline-secondary" href="<?=APP::config('url') ?>doktor/novi">Dodaj novog doktora</a>
<?php endif; ?>