<div class="container center_div">
    <div class="div-wrapper d-flex justify-content-center align-items-center">
        <form action="<?=APP::config('url') ?>doktor/novi" method="POST">
            
            <h1 class="h3 mb-3 font-weight-normal">Dodaj novog doktora</h1>

            <div class="form-group">
                <label>Ime:
                    <input type="text" name="ime" class="form-control text-center">
                </label>    
                <br>    
            </div>
            
            <div class="form-group">
                <label>Prezime:
                    <input type="text" name="prezime" class="form-control text-center">
                </label>    
                <br>    
            </div>

            <div class="form-group">
                <label>IBAN:
                    <input type="text" name="iban" class="form-control text-center">
                </label>    
                <br>    
            </div>

            <div class="dropdown">
                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    Odaberi ordinaciju
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                    <?php foreach ($ordinacije as $ordinacija): ?>
                    <a class="dropdown-item" href=""><?=$ordinacija->naziv ?></a>
                <?php endforeach; ?>
                </div>
            </div>
            
            <button class="btn btn-primary" type="submit">Unesi</button>
            
            <br>
            
            
        </form>
    </div>
</div>