<div class="container center_div">
    <div class="div-wrapper d-flex justify-content-center align-items-center">
        <form action="<?=APP::config('url') ?>doktor/novi" method="POST">
            
            <h1 class="h3 mb-3 font-weight-normal">Dodaj novog doktora</h1>

            <div class="form-group">
                <label>Ime:
                    <input type="text" name="ime" class="form-control text-center" value="<?php $entitet->ime; ?>">
                </label>    
                <br>    
            </div>
            
            <div class="form-group">
                <label>Prezime:
                    <input type="text" name="prezime" class="form-control text-center" value="<?php $entitet->prezime; ?>">
                </label>    
                <br>    
            </div>

            <div class="form-group">
                <label>IBAN:
                    <input type="text" name="iban" class="form-control text-center" value="<?php $entitet->iban; ?>">
                </label>    
                <br>    
            </div>

            <div class="form-group">
                <label >Ordinacija:</label>
                <select name="ordinacija" id="ordinacija" class="form-control">
                    <option selected>Odaberi...</option>
                    <?php foreach($ordinacije as $ordinacija): ?>
                        <option <?php if($entitet->ordinacija==$ordinacija->sifra){ echo ' selected="selected"';} ?>
                        Value="<?=$ordinacija->sifra?>"><?=$ordinacija->naziv?></option>
                    <?php endforeach; ?>
                </select>
            </div>

                 
            
            <button class="btn btn-primary" type="submit">Unesi</button>
            
            <br>
            
            
        </form>
    </div>
</div>