<div class="container center_div">
    <div class="div-wrapper d-flex justify-content-center align-items-center">
        <form action="<?=APP::config('url') ?>doktor/promjena" method="POST">
            
            <h1 class="h3 mb-3 font-weight-normal">Promijeni podatke</h1>

            <div class="form-group">
                <label>Ime:
                    <input type="text" name="ime" class="form-control text-center" value="<?=$entitet->ime?>">
                </label>    
                <br>    
            </div>
            
            <div class="form-group">
                <label>Prezime:
                    <input type="text" name="prezime" class="form-control text-center" value="<?=$entitet->prezime?>">
                </label>    
                <br>    
            </div>

            <div class="form-group">
                <label>IBAN:
                    <input type="text" name="iban" class="form-control text-center" value="<?=$entitet->iban?>">
                </label>
                <br>    
            </div>

            <div class="form-group">
        <label for="inputState">Ordinacija:</label>
            <select id="inputState" class="form-control">
                <option selected>Odaberi...</option>
                
            </select>
        </div>

            
            
            <button class="btn btn-primary" type="submit">Promijeni</button>
            
            <br>
            
            <?=$poruka; ?>
        </form>
    </div>
</div>