<!DOCTYPE html>
<html lang="en">
<head>
<?php include_once 'predlozak/skripte.phtml'; ?>
    <?php include_once 'predlozak/head.phtml'; ?>
    <br>
</head>
<body>
    <div class = container>
        <?php include_once 'predlozak/izbornik.phtml'; ?>
        <br>
        

        <div class= 'large-12 small-12'>
            <div class='card' style="min-height: 400px">
                <div class='container'>
                    <?php echo $sadrzaj; ?> 
                </div>                
            </div>            
        </div>

        <br>
    
        <?php include_once 'predlozak/podnozje.phtml'; ?>
    </div>

    <?php include_once 'predlozak/skripte.phtml'; ?>

</body>
</html>